name = "stratokit-app"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "stratokit-db"
database_id = "51fb47ef-dead-4e86-863c-1d537f46896c"

[ai]
binding = "AI"
